sudo: required
dist: trusty

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

language: node_js

jobs:
  include:
    - stage: Docker Setup
      script:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO=oisann/twitter-notifications
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - stage: Docker Build
      script:
        - docker build -f Dockerfile -t $REPO:$COMMIT .
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - stage: Deploy docker image
      script:
        - docker push $REPO
    - stage: test
      script: docker run --rm $REPO:travis-$TRAVIS_BUILD_NUMBER npm test